CREATE SCHEMA human_activity;

DROP TABLE IF EXISTS ha_dataset;
CREATE TABLE ha_dataset (
user_id VARCHAR(100) NOT NULL,
timestamp DATETIME NOT NULL,
acc_magnitude_mean DOUBLE PRECISION NOT NULL,
acc_magnitude_std DOUBLE PRECISION NOT NULL,
acc_magnitude_value_entropy DOUBLE PRECISION NOT NULL,
acc_magnitude_time_entropy DOUBLE PRECISION NOT NULL,
acc_spec_spectral_entropy DOUBLE PRECISION NOT NULL,
acc_3d_mean_x DOUBLE PRECISION NOT NULL,
acc_3d_mean_y DOUBLE PRECISION NOT NULL,
acc_3d_mean_z DOUBLE PRECISION NOT NULL,
acc_3d_std_x DOUBLE PRECISION NOT NULL,
acc_3d_std_y DOUBLE PRECISION NOT NULL,
acc_3d_std_z DOUBLE PRECISION NOT NULL,
acc_3d_ro_x DOUBLE PRECISION NOT NULL,
acc_3d_ro_y DOUBLE PRECISION NOT NULL,
acc_3d_ro_z DOUBLE PRECISION NOT NULL,
gyro_magnitude_mean DOUBLE PRECISION NOT NULL,
gyro_magnitude_std DOUBLE PRECISION NOT NULL,
gyro_magnitude_value_entropy DOUBLE PRECISION NOT NULL,
gyro_magnitude_time_entropy DOUBLE PRECISION NOT NULL,
gyro_spec_spectral_entropy DOUBLE PRECISION NOT NULL,
gyro_3d_mean_x DOUBLE PRECISION NOT NULL,
gyro_3d_mean_y DOUBLE PRECISION NOT NULL,
gyro_3d_mean_z DOUBLE PRECISION NOT NULL,
gyro_3d_std_x DOUBLE PRECISION NOT NULL,
gyro_3d_std_y DOUBLE PRECISION NOT NULL,
gyro_3d_std_z DOUBLE PRECISION NOT NULL,
gyro_3d_ro_xy DOUBLE PRECISION NOT NULL,
gyro_3d_ro_xz DOUBLE PRECISION NOT NULL,
gyro_3d_ro_yz DOUBLE PRECISION NOT NULL,
magnet_magnitude_mean DOUBLE PRECISION NOT NULL,
magnet_magnitude_std DOUBLE PRECISION NOT NULL,
magnet_magnitude_value_entropy DOUBLE PRECISION NOT NULL,
magnet_magnitude_time_entropy DOUBLE PRECISION NOT NULL,
magnet_spec_spectral_entropy DOUBLE PRECISION NOT NULL,
magnet_3d_mean_x DOUBLE PRECISION NOT NULL,
magnet_3d_mean_y DOUBLE PRECISION NOT NULL,
magnet_3d_mean_z DOUBLE PRECISION NOT NULL,
magnet_3d_std_x DOUBLE PRECISION NOT NULL,
magnet_3d_std_y DOUBLE PRECISION NOT NULL,
magnet_3d_std_z DOUBLE PRECISION NOT NULL,
magnet_3d_ro_xy DOUBLE PRECISION NOT NULL,
magnet_3d_ro_xz DOUBLE PRECISION NOT NULL,
magnet_3d_ro_yz DOUBLE PRECISION NOT NULL,
acc_watch_magnitude_mean DOUBLE PRECISION NOT NULL,
acc_watch_magnitude_std DOUBLE PRECISION NOT NULL,
acc_watch_magnitude_value_entropy DOUBLE PRECISION NOT NULL,
acc_watch_magnitude_time_entropy DOUBLE PRECISION NOT NULL,
acc_watch_spec_spectral_entropy DOUBLE PRECISION NOT NULL,
acc_watch_3d_mean_x DOUBLE PRECISION NOT NULL,
acc_watch_3d_mean_y DOUBLE PRECISION NOT NULL,
acc_watch_3d_mean_z DOUBLE PRECISION NOT NULL,
acc_watch_3d_std_x DOUBLE PRECISION NOT NULL,
acc_watch_3d_std_y DOUBLE PRECISION NOT NULL,
acc_watch_3d_std_z DOUBLE PRECISION NOT NULL,
acc_watch_3d_ro_xy DOUBLE PRECISION NOT NULL,
acc_watch_3d_ro_xz DOUBLE PRECISION NOT NULL,
acc_watch_3d_ro_yz DOUBLE PRECISION NOT NULL,
loc_valid_updates INT NOT NULL,
loc_log_latitude_range DOUBLE PRECISION NOT NULL,
loc_log_longitude_range DOUBLE PRECISION NOT NULL,
loc_min_altitude DOUBLE PRECISION NOT NULL,
loc_max_altitude DOUBLE PRECISION NOT NULL,
loc_best_horizontal_accuracy DOUBLE PRECISION NOT NULL,
loc_best_vertical_accuracy DOUBLE PRECISION NOT NULL,
loc_diameter DOUBLE PRECISION NOT NULL,
loc_log_diameter DOUBLE PRECISION NOT NULL,
loc_features_std_lat DOUBLE PRECISION NOT NULL,
loc_features_std_long DOUBLE PRECISION NOT NULL,
loc_features_lat_change DOUBLE PRECISION NOT NULL,
loc_features_log_change DOUBLE PRECISION NOT NULL,
loc_features_mean_abs_lat_deriv DOUBLE PRECISION NOT NULL,
loc_features_mean_abs_long_deriv DOUBLE PRECISION NOT NULL,
time_of_day_between0_6 INT NOT NULL,
time_of_day_between3_9 INT NOT NULL,
time_of_day_between6_12 INT NOT NULL,
time_of_day_between9_15 INT NOT NULL,
time_of_day_between12_18 INT NOT NULL,
time_of_day_between15_21 INT NOT NULL,
time_of_day_between18_24 INT NOT NULL,
time_of_day_between21_3 INT NOT NULL,
lab_new_geographical_displac INT NOT NULL,
lab_new_geographical_locat INT NOT NULL
);

