CREATE SCHEMA human_activity;

DROP TABLE IF EXISTS ha_dataset;
CREATE TABLE ha_dataset (
timestamp DATETIME NOT NULL,
acc_magnitude_mean DOUBLE PRECISION NOT NULL,
acc_magnitude_std DOUBLE PRECISION NOT NULL,
acc_magnitude_moment3 DOUBLE PRECISION NOT NULL,
acc_magnitude_moment4 DOUBLE PRECISION NOT NULL,
acc_magnitude_perc25 DOUBLE PRECISION NOT NULL,
acc_magnitude_perc50 DOUBLE PRECISION NOT NULL,
acc_magnitude_perc75 DOUBLE PRECISION NOT NULL,
acc_magnitude_value_entropy DOUBLE PRECISION NOT NULL,
acc_magnitude_time_entropy DOUBLE PRECISION NOT NULL,
acc_spec_log_energy0 DOUBLE PRECISION NOT NULL,
acc_spec_log_energy1 DOUBLE PRECISION NOT NULL,
acc_spec_log_energy2 DOUBLE PRECISION NOT NULL,
acc_spec_log_energy3 DOUBLE PRECISION NOT NULL,
acc_spec_log_energy4 DOUBLE PRECISION NOT NULL,
acc_spec_spectral_entropy DOUBLE PRECISION NOT NULL,
acc_3d_mean_x DOUBLE PRECISION NOT NULL,
acc_3d_mean_y DOUBLE PRECISION NOT NULL,
acc_3d_mean_z DOUBLE PRECISION NOT NULL,
acc_3d_std_x DOUBLE PRECISION NOT NULL,
acc_3d_std_y DOUBLE PRECISION NOT NULL,
acc_3d_std_z DOUBLE PRECISION NOT NULL,
acc_3d_ro_x DOUBLE PRECISION NOT NULL,
acc_3d_ro_y DOUBLE PRECISION NOT NULL,
acc_3d_ro_z DOUBLE PRECISION NOT NULL,
gyro_magnitude_mean DOUBLE PRECISION NOT NULL,
gyro_magnitude_std DOUBLE PRECISION NOT NULL,
gyro_magnitude_moment3 DOUBLE PRECISION NOT NULL,
gyro_magnitude_moment4 DOUBLE PRECISION NOT NULL,
gyro_magnitude_perc25 DOUBLE PRECISION NOT NULL,
gyro_magnitude_perc50 DOUBLE PRECISION NOT NULL,
gyro_magnitude_perc75 DOUBLE PRECISION NOT NULL,
gyro_magnitude_value_entropy DOUBLE PRECISION NOT NULL,
gyro_magnitude_time_entropy DOUBLE PRECISION NOT NULL,
gyro_spec_log_energy0 DOUBLE PRECISION NOT NULL,
gyro_spec_log_energy1 DOUBLE PRECISION NOT NULL,
gyro_spec_log_energy2 DOUBLE PRECISION NOT NULL,
gyro_spec_log_energy3 DOUBLE PRECISION NOT NULL,
gyro_spec_log_energy4 DOUBLE PRECISION NOT NULL,
gyro_spec_spectral_entropy DOUBLE PRECISION NOT NULL,
gyro_3d_mean_x DOUBLE PRECISION NOT NULL,
gyro_3d_mean_y DOUBLE PRECISION NOT NULL,
gyro_3d_mean_z DOUBLE PRECISION NOT NULL,
gyro_3d_std_x DOUBLE PRECISION NOT NULL,
gyro_3d_std_y DOUBLE PRECISION NOT NULL,
gyro_3d_std_z DOUBLE PRECISION NOT NULL,
gyro_3d_ro_xy DOUBLE PRECISION NOT NULL,
gyro_3d_ro_xz DOUBLE PRECISION NOT NULL,
gyro_3d_ro_yz DOUBLE PRECISION NOT NULL,
magnet_magnitude_mean DOUBLE PRECISION NOT NULL,
magnet_magnitude_std DOUBLE PRECISION NOT NULL,
magnet_magnitude_moment3 DOUBLE PRECISION NOT NULL,
magnet_magnitude_moment4 DOUBLE PRECISION NOT NULL,
magnet_magnitude_perc25 DOUBLE PRECISION NOT NULL,
magnet_magnitude_perc50 DOUBLE PRECISION NOT NULL,
magnet_magnitude_perc75 DOUBLE PRECISION NOT NULL,
magnet_magnitude_value_entropy DOUBLE PRECISION NOT NULL,
magnet_magnitude_time_entropy DOUBLE PRECISION NOT NULL,
magnet_spec_log_energy0 DOUBLE PRECISION NOT NULL,
magnet_spec_log_energy1 DOUBLE PRECISION NOT NULL,
magnet_spec_log_energy2 DOUBLE PRECISION NOT NULL,
magnet_spec_log_energy3 DOUBLE PRECISION NOT NULL,
magnet_spec_log_energy4 DOUBLE PRECISION NOT NULL,
magnet_spec_spectral_entropy DOUBLE PRECISION NOT NULL,
magnet_3d_mean_x DOUBLE PRECISION NOT NULL,
magnet_3d_mean_y DOUBLE PRECISION NOT NULL,
magnet_3d_mean_z DOUBLE PRECISION NOT NULL,
magnet_3d_std_x DOUBLE PRECISION NOT NULL,
magnet_3d_std_y DOUBLE PRECISION NOT NULL,
magnet_3d_std_z DOUBLE PRECISION NOT NULL,
magnet_3d_ro_xy DOUBLE PRECISION NOT NULL,
magnet_3d_ro_xz DOUBLE PRECISION NOT NULL,
magnet_3d_ro_yz DOUBLE PRECISION NOT NULL,
magnet_avr_cos_similarity_lag0 DOUBLE PRECISION NOT NULL,
magnet_avr_cos_similarity_lag1 DOUBLE PRECISION NOT NULL,
magnet_avr_cos_similarity_lag2 DOUBLE PRECISION NOT NULL,
magnet_avr_cos_similarity_lag3 DOUBLE PRECISION NOT NULL,
magnet_avr_cos_similarity_lag4 DOUBLE PRECISION NOT NULL,
acc_watch_magnitude_mean DOUBLE PRECISION NOT NULL,
acc_watch_magnitude_std DOUBLE PRECISION NOT NULL,
acc_watch_magnitude_moment3 DOUBLE PRECISION NOT NULL,
acc_watch_magnitude_moment4 DOUBLE PRECISION NOT NULL,
acc_watch_magnitude_perc25 DOUBLE PRECISION NOT NULL,
acc_watch_magnitude_perc50 DOUBLE PRECISION NOT NULL,
acc_watch_magnitude_perc75 DOUBLE PRECISION NOT NULL,
acc_watch_magnitude_value_entropy DOUBLE PRECISION NOT NULL,
acc_watch_magnitude_time_entropy DOUBLE PRECISION NOT NULL,
acc_watch_spec_log_energy0 DOUBLE PRECISION NOT NULL,
acc_watch_spec_log_energy1 DOUBLE PRECISION NOT NULL,
acc_watch_spec_log_energy2 DOUBLE PRECISION NOT NULL,
acc_watch_spec_log_energy3 DOUBLE PRECISION NOT NULL,
acc_watch_spec_log_energy4 DOUBLE PRECISION NOT NULL,
acc_watch_spec_spectral_entropy DOUBLE PRECISION NOT NULL,
acc_watch_3d_mean_x DOUBLE PRECISION NOT NULL,
acc_watch_3d_mean_y DOUBLE PRECISION NOT NULL,
acc_watch_3d_mean_z DOUBLE PRECISION NOT NULL,
acc_watch_3d_std_x DOUBLE PRECISION NOT NULL,
acc_watch_3d_std_y DOUBLE PRECISION NOT NULL,
acc_watch_3d_std_z DOUBLE PRECISION NOT NULL,
acc_watch_3d_ro_xy DOUBLE PRECISION NOT NULL,
acc_watch_3d_ro_xz DOUBLE PRECISION NOT NULL,
acc_watch_3d_ro_yz DOUBLE PRECISION NOT NULL,
acc_watch_spec_x_log_energy0 DOUBLE PRECISION NOT NULL,
acc_watch_spec_x_log_energy1 DOUBLE PRECISION NOT NULL,
acc_watch_spec_x_log_energy2 DOUBLE PRECISION NOT NULL,
acc_watch_spec_x_log_energy3 DOUBLE PRECISION NOT NULL,
acc_watch_spec_x_log_energy4 DOUBLE PRECISION NOT NULL,
acc_watch_spec_y_log_energy0 DOUBLE PRECISION NOT NULL,
acc_watch_spec_y_log_energy1 DOUBLE PRECISION NOT NULL,
acc_watch_spec_y_log_energy2 DOUBLE PRECISION NOT NULL,
acc_watch_spec_y_log_energy3 DOUBLE PRECISION NOT NULL,
acc_watch_spec_y_log_energy4 DOUBLE PRECISION NOT NULL,
acc_watch_spec_z_log_energy0 DOUBLE PRECISION NOT NULL,
acc_watch_spec_z_log_energy1 DOUBLE PRECISION NOT NULL,
acc_watch_spec_z_log_energy2 DOUBLE PRECISION NOT NULL,
acc_watch_spec_z_log_energy3 DOUBLE PRECISION NOT NULL,
acc_watch_spec_z_log_energy4 DOUBLE PRECISION NOT NULL,
acc_watch_avr_cos_similarity_lag0 DOUBLE PRECISION NOT NULL,
acc_watch_avr_cos_similarity_lag1 DOUBLE PRECISION NOT NULL,
acc_watch_avr_cos_similarity_lag2 DOUBLE PRECISION NOT NULL,
acc_watch_avr_cos_similarity_lag3 DOUBLE PRECISION NOT NULL,
acc_watch_avr_cos_similarity_lag4 DOUBLE PRECISION NOT NULL,
loc_valid_updates INT NOT NULL,
loc_log_latitude_range DOUBLE PRECISION NOT NULL,
loc_log_longitude_range DOUBLE PRECISION NOT NULL,
loc_min_altitude DOUBLE PRECISION NOT NULL,
loc_max_altitude DOUBLE PRECISION NOT NULL,
loc_best_horizontal_accuracy DOUBLE PRECISION NOT NULL,
loc_best_vertical_accuracy DOUBLE PRECISION NOT NULL,
loc_diameter DOUBLE PRECISION NOT NULL,
loc_log_diameter DOUBLE PRECISION NOT NULL,
loc_features_std_lat DOUBLE PRECISION NOT NULL,
loc_features_std_long DOUBLE PRECISION NOT NULL,
loc_features_lat_change DOUBLE PRECISION NOT NULL,
loc_features_log_change DOUBLE PRECISION NOT NULL,
loc_features_mean_abs_lat_deriv DOUBLE PRECISION NOT NULL,
loc_features_mean_abs_long_deriv DOUBLE PRECISION NOT NULL,
discrete_state_active INT NOT NULL,
discrete_state_inactive INT NOT NULL,
discrete_state_background INT NOT NULL,
discrete_state_missing INT NOT NULL,
discrete_plugged_ac INT NOT NULL,
discrete_plugged_usb INT NOT NULL,
discrete_plugged_wireless INT NOT NULL,
discrete_plugged_missing INT NOT NULL,
discrete_battery_unknown INT NOT NULL,
discrete_battery_unplugged INT NOT NULL,
discrete_battery_nocharging INT NOT NULL,
discrete_battery_discharging INT NOT NULL,
discrete_battery_charging INT NOT NULL,
discrete_battery_full INT NOT NULL,
discrete_battery_missing INT NOT NULL,
discrete_on_phone_False INT NOT NULL,
discrete_on_phone_True INT NOT NULL,
discrete_on_phone_missing INT NOT NULL,
discrete_ringer_normal INT NOT NULL,
discrete_ringer_silent_novibrate INT NOT NULL,
discrete_ringer_silent_vibrate INT NOT NULL,
discrete_ringer_ringer_missing INT NOT NULL,
discrete_wifi_noreachable INT NOT NULL,
discrete_wifi_reachable_via_wifi INT NOT NULL,
discrete_wifi_reachable_via_wwan INT NOT NULL,
discrete_wifi_missing INT NOT NULL,
lf_meas_proximity_cm INT NOT NULL,
lf_meas_proximity DOUBLE PRECISION NOT NULL,
lf_meas_battery_level DOUBLE PRECISION NOT NULL,
lf_meas_screen_brightness DOUBLE PRECISION NOT NULL,
time_of_day_between0_6 INT NOT NULL,
time_of_day_between3_9 INT NOT NULL,
time_of_day_between6_12 INT NOT NULL,
time_of_day_between9_15 INT NOT NULL,
time_of_day_between12_18 INT NOT NULL,
time_of_day_between15_21 INT NOT NULL,
time_of_day_between18_24 INT NOT NULL,
time_of_day_between21_3 INT NOT NULL,
lab_LYING_DOWN INT NOT NULL,
lab_SITTING INT NOT NULL,
lab_FIX_walking INT NOT NULL,
lab_FIX_running INT NOT NULL,
lab_BICYCLING INT NOT NULL,
lab_SLEEPING INT NOT NULL,
lab_LAB_WORK INT NOT NULL,
lab_IN_CLASS INT NOT NULL,
lab_IN_A_MEETING INT NOT NULL,
lab_LOC_main_workplace INT NOT NULL,
lab_OR_indoors INT NOT NULL,
lab_OR_outside INT NOT NULL,
lab_IN_A_CAR INT NOT NULL,
lab_ON_A_BUS INT NOT NULL,
lab_DRIVE_I_M_THE_DRIVER INT NOT NULL,
lab_DRIVE_I_M_A_PASSENGER INT NOT NULL,
lab_LOC_home INT NOT NULL,
lab_FIX_restaurant INT NOT NULL,
lab_PHONE_IN_POCKET INT NOT NULL,
lab_OR_exercise INT NOT NULL,
lab_COOKING INT NOT NULL,
lab_SHOPPING INT NOT NULL,
lab_STROLLING INT NOT NULL,
lab_DRINKING__ALCOHOL_ INT NOT NULL,
lab_BATHING_SHOWER INT NOT NULL,
lab_CLEANING INT NOT NULL,
lab_DOING_LAUNDRY INT NOT NULL,
lab_WASHING_DISHES INT NOT NULL,
lab_WATCHING_TV INT NOT NULL,
lab_SURFING_THE_INTERNET INT NOT NULL,
lab_AT_A_PARTY INT NOT NULL,
lab_AT_A_BAR INT NOT NULL,
lab_LOC_beach INT NOT NULL,
lab_SINGING INT NOT NULL,
lab_TALKING INT NOT NULL,
lab_COMPUTER_WORK INT NOT NULL,
lab_EATING INT NOT NULL,
lab_TOILET INT NOT NULL,
lab_GROOMING INT NOT NULL,
lab_DRESSING INT NOT NULL,
lab_AT_THE_GYM INT NOT NULL,
lab_STAIRS_GOING_UP INT NOT NULL,
lab_STAIRS_GOING_DOWN INT NOT NULL,
lab_ELEVATOR INT NOT NULL,
lab_OR_standing INT NOT NULL,
lab_AT_SCHOOL INT NOT NULL,
lab_PHONE_IN_HAND INT NOT NULL,
lab_PHONE_IN_BAG INT NOT NULL,
lab_PHONE_ON_TABLE INT NOT NULL,
lab_WITH_COWORKERS INT NOT NULL,
lab_WITH_FRIENDS INT NOT NULL,
lab_new_geographical_displac INT NOT NULL
);

